#!/bin/sh

#Default values
export ARTIFACTORY_HOME=/opt/artifactory-oss-6.13.1
export ARTIFACTORY_USER=artifactory
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
#export START_LOCAL_REPLICATOR=true

#export START_LOCAL_MDS=true
#export START_LOCAL_ROUTER=true

export TOMCAT_HOME=/opt/artifactory-oss-6.13.1/tomcat
export ARTIFACTORY_PID=$ARTIFACTORY_HOME/run/artifactory.pid

export JAVA_OPTIONS="-server -Xms512m -Xmx4g -Xss256k -XX:+UseG1GC -XX:OnOutOfMemoryError=\"kill -9 %p\""
export JAVA_OPTIONS="$JAVA_OPTIONS -Djruby.compile.invokedynamic=false -Dfile.encoding=UTF8 -Dartdist=zip -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true -Djava.security.egd=file:/dev/./urandom"
# Timeout waiting for artifactory to start
# START_TMO=60